// The Trivia Night question bank.
//
// A curated bank checked into the repo, never generated during a game: a wrong
// answer key marks a right player wrong with no appeal, so every answer here
// was written with its question. Keep entries mainstream — the kind of thing a
// table of friends has a fair shot at — and write each question so it works
// both read aloud with no options (host mode) and as multiple choice (no-host
// mode). That means the question alone must pin down one answer.
//
// Entry format: [question, answer, [three wrong answers]]
// Spelling entries are { word, sentence, wrong } and are turned into questions
// below, because the host and the phones need to see different things.

const CATEGORIES = [
  {
    id: 'geography', name: 'Geography', icon: '🌍',
    questions: [
      ['What is the capital of Australia?', 'Canberra', ['Sydney', 'Melbourne', 'Perth']],
      ['What is the longest river in Africa?', 'The Nile', ['The Congo', 'The Niger', 'The Zambezi']],
      ['What is the largest ocean on Earth?', 'The Pacific', ['The Atlantic', 'The Indian', 'The Arctic']],
      ['Which country has the largest population in South America?', 'Brazil', ['Argentina', 'Colombia', 'Peru']],
      ['Mount Everest sits on the border between Nepal and which other country?', 'China', ['India', 'Bhutan', 'Pakistan']],
      ['What is the capital of Canada?', 'Ottawa', ['Toronto', 'Vancouver', 'Montreal']],
      ['What is the largest hot desert in the world?', 'The Sahara', ['The Gobi', 'The Kalahari', 'The Mojave']],
      ['Which US state is made up entirely of islands?', 'Hawaii', ['Alaska', 'Florida', 'Rhode Island']],
      ['What is the smallest country in the world by area?', 'Vatican City', ['Monaco', 'San Marino', 'Liechtenstein']],
      ['Which continent has the most countries?', 'Africa', ['Asia', 'Europe', 'South America']],
      ['In which country would you find Machu Picchu?', 'Peru', ['Mexico', 'Chile', 'Bolivia']],
      ['Which river flows through Paris?', 'The Seine', ['The Thames', 'The Danube', 'The Rhine']],
      ['What is the largest country in the world by area?', 'Russia', ['Canada', 'China', 'The United States']],
      ['In which country is the city of Marrakech?', 'Morocco', ['Egypt', 'Tunisia', 'Algeria']],
      ['The Great Barrier Reef lies off the coast of which country?', 'Australia', ['Indonesia', 'The Philippines', 'New Zealand']],
      ['What is the capital of Spain?', 'Madrid', ['Barcelona', 'Seville', 'Valencia']],
      ['Which US state is nicknamed the Sunshine State?', 'Florida', ['California', 'Arizona', 'Hawaii']],
      ['Which European country is shaped like a boot?', 'Italy', ['Greece', 'Portugal', 'Croatia']],
      ['What is the tallest waterfall in the world?', 'Angel Falls', ['Niagara Falls', 'Victoria Falls', 'Iguazu Falls']],
      ['Which two countries share the longest land border in the world?', 'Canada and the United States', ['Russia and China', 'Argentina and Chile', 'Russia and Kazakhstan']],
      ['What is the capital of Egypt?', 'Cairo', ['Alexandria', 'Luxor', 'Giza']],
      ['What is the capital of Japan?', 'Tokyo', ['Kyoto', 'Osaka', 'Hiroshima']],
    ],
  },
  {
    id: 'science', name: 'Science', icon: '🔬',
    questions: [
      ['What gas do plants take in from the air for photosynthesis?', 'Carbon dioxide', ['Oxygen', 'Nitrogen', 'Hydrogen']],
      ['What is the chemical symbol for gold?', 'Au', ['Ag', 'Gd', 'Go']],
      ['Which planet is known as the Red Planet?', 'Mars', ['Jupiter', 'Venus', 'Mercury']],
      ['What is the hardest natural substance?', 'Diamond', ['Quartz', 'Granite', 'Iron']],
      ['How many bones are in the adult human body?', '206', ['186', '212', '256']],
      ['What is the largest planet in our solar system?', 'Jupiter', ['Saturn', 'Neptune', 'Uranus']],
      ['Which part of a cell is known as its powerhouse?', 'The mitochondria', ['The nucleus', 'The ribosome', 'The cell membrane']],
      ['At what temperature in Celsius does water boil at sea level?', '100°C', ['90°C', '110°C', '212°C']],
      ['Which planet is closest to the Sun?', 'Mercury', ['Venus', 'Mars', 'Earth']],
      ['What is the largest organ of the human body?', 'The skin', ['The liver', 'The brain', 'The lungs']],
      ['Who came up with the theory of relativity?', 'Albert Einstein', ['Isaac Newton', 'Nikola Tesla', 'Stephen Hawking']],
      ['What is the chemical symbol for sodium?', 'Na', ['So', 'Sd', 'S']],
      ['How many planets are in our solar system?', '8', ['7', '9', '10']],
      ['Is a dolphin a fish, a mammal, a reptile or an amphibian?', 'A mammal', ['A fish', 'A reptile', 'An amphibian']],
      ['What do bees collect from flowers to make honey?', 'Nectar', ['Pollen', 'Sap', 'Dew']],
      ['Which blood cells fight infection?', 'White blood cells', ['Red blood cells', 'Platelets', 'Plasma cells']],
      ['What is the most common gas in Earth’s atmosphere?', 'Nitrogen', ['Oxygen', 'Carbon dioxide', 'Argon']],
      ['What is the closest star to Earth?', 'The Sun', ['Proxima Centauri', 'Sirius', 'Polaris']],
      ['What force pulls objects toward the center of the Earth?', 'Gravity', ['Magnetism', 'Friction', 'Inertia']],
      ['What is the freezing point of water in Fahrenheit?', '32°F', ['0°F', '40°F', '12°F']],
      ['Which organ pumps blood around the body?', 'The heart', ['The lungs', 'The liver', 'The kidneys']],
    ],
  },
  {
    id: 'history', name: 'History', icon: '📜',
    questions: [
      ['Who was the first President of the United States?', 'George Washington', ['Thomas Jefferson', 'Abraham Lincoln', 'John Adams']],
      ['In what year did World War II end?', '1945', ['1944', '1939', '1918']],
      ['Who was the first person to walk on the Moon?', 'Neil Armstrong', ['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn']],
      ['Which ancient civilization built the pyramids of Giza?', 'The Egyptians', ['The Romans', 'The Greeks', 'The Maya']],
      ['In what year did the Titanic sink?', '1912', ['1905', '1920', '1915']],
      ['Who was the British Prime Minister for most of World War II?', 'Winston Churchill', ['Neville Chamberlain', 'Clement Attlee', 'Margaret Thatcher']],
      ['Which wall, dividing a city, fell in 1989?', 'The Berlin Wall', ['Hadrian’s Wall', 'The Great Wall', 'The Western Wall']],
      ['Julius Caesar was a leader of which ancient civilization?', 'Rome', ['Greece', 'Egypt', 'Persia']],
      ['Who was the main author of the Declaration of Independence?', 'Thomas Jefferson', ['Benjamin Franklin', 'John Adams', 'George Washington']],
      ['Who was the first woman to fly solo across the Atlantic Ocean?', 'Amelia Earhart', ['Bessie Coleman', 'Sally Ride', 'Valentina Tereshkova']],
      ['Which ship carried the Pilgrims to America in 1620?', 'The Mayflower', ['The Santa Maria', 'The Endeavour', 'The Beagle']],
      ['Who painted the Mona Lisa?', 'Leonardo da Vinci', ['Michelangelo', 'Raphael', 'Vincent van Gogh']],
      ['Which country gave the Statue of Liberty to the United States?', 'France', ['Britain', 'Spain', 'Italy']],
      ['In which city was President John F. Kennedy assassinated?', 'Dallas', ['Houston', 'Washington, D.C.', 'Chicago']],
      ['What was the name of the first artificial satellite sent into space?', 'Sputnik 1', ['Explorer 1', 'Vostok 1', 'Apollo 1']],
      ['Which civil rights leader gave the “I Have a Dream” speech?', 'Martin Luther King Jr.', ['Malcolm X', 'Frederick Douglass', 'John Lewis']],
      ['Which French military leader crowned himself Emperor in 1804?', 'Napoleon Bonaparte', ['Louis XIV', 'Charlemagne', 'Joan of Arc']],
      ['Which US president issued the Emancipation Proclamation?', 'Abraham Lincoln', ['George Washington', 'Ulysses S. Grant', 'Andrew Jackson']],
      ['What was the name of the ship Charles Darwin sailed on?', 'HMS Beagle', ['HMS Victory', 'The Endeavour', 'The Mayflower']],
      ['Which explorer’s 1492 voyage reached the Americas?', 'Christopher Columbus', ['Ferdinand Magellan', 'Vasco da Gama', 'Marco Polo']],
    ],
  },
  {
    id: 'harry-potter', name: 'Harry Potter', icon: '⚡',
    questions: [
      ['Which Hogwarts house is Harry Potter sorted into?', 'Gryffindor', ['Slytherin', 'Ravenclaw', 'Hufflepuff']],
      ['What is the name of Harry’s snowy owl?', 'Hedwig', ['Errol', 'Pigwidgeon', 'Hermes']],
      ['What position does Harry play on the Quidditch team?', 'Seeker', ['Keeper', 'Chaser', 'Beater']],
      ['Which platform does the Hogwarts Express leave from?', 'Platform 9¾', ['Platform 7½', 'Platform 10¾', 'Platform 9½']],
      ['Who is the Half-Blood Prince?', 'Severus Snape', ['Tom Riddle', 'Harry Potter', 'Remus Lupin']],
      ['What is the name of the Weasley family home?', 'The Burrow', ['Shell Cottage', 'Grimmauld Place', 'The Nest']],
      ['Which spell knocks the wand out of an opponent’s hand?', 'Expelliarmus', ['Expecto Patronum', 'Stupefy', 'Alohomora']],
      ['Which creatures guard the wizard prison Azkaban?', 'Dementors', ['Trolls', 'Goblins', 'Hippogriffs']],
      ['What is Hermione’s last name?', 'Granger', ['Weasley', 'Lovegood', 'Brown']],
      ['Which magical map shows where everyone is at Hogwarts?', 'The Marauder’s Map', ['The Mirror of Erised', 'The Pensieve', 'The Sneakoscope']],
      ['What is the name of Hagrid’s three-headed dog?', 'Fluffy', ['Fang', 'Norbert', 'Buckbeak']],
      ['Which house-elf is set free when Harry tricks Lucius Malfoy with a sock?', 'Dobby', ['Kreacher', 'Winky', 'Hokey']],
      ['What is the name of the wizarding bank run by goblins?', 'Gringotts', ['Ollivanders', 'Borgin and Burkes', 'Flourish and Blotts']],
      ['What animal is Harry’s Patronus?', 'A stag', ['A doe', 'An otter', 'A phoenix']],
      ['Which ghost haunts a girls’ bathroom at Hogwarts?', 'Moaning Myrtle', ['Nearly Headless Nick', 'The Grey Lady', 'The Fat Friar']],
      ['What is Lord Voldemort’s real name?', 'Tom Marvolo Riddle', ['Tom Gaunt', 'Marvolo Slytherin', 'Morfin Riddle']],
      ['What does the spell “Lumos” do?', 'Lights up the tip of your wand', ['Unlocks doors', 'Makes objects float', 'Summons objects']],
      ['Which house is Luna Lovegood in?', 'Ravenclaw', ['Hufflepuff', 'Gryffindor', 'Slytherin']],
      ['What is the name of the sport played on broomsticks?', 'Quidditch', ['Gobstones', 'Quodpot', 'Broomball']],
      ['What is the name of Ron’s pet rat?', 'Scabbers', ['Crookshanks', 'Trevor', 'Nagini']],
      ['Which object reflects your deepest desire when you look into it?', 'The Mirror of Erised', ['The Goblet of Fire', 'The Sorting Hat', 'The Pensieve']],
    ],
  },
  {
    id: 'percy-jackson', name: 'Percy Jackson', icon: '🔱',
    questions: [
      ['Who is Percy Jackson’s godly parent?', 'Poseidon', ['Zeus', 'Hades', 'Apollo']],
      ['What is the name of the camp where Greek demigods train?', 'Camp Half-Blood', ['Camp Jupiter', 'Camp Olympus', 'Camp Crystal Lake']],
      ['What is the name of Percy’s sword?', 'Riptide', ['Backbiter', 'Katoptris', 'Frostbite']],
      ['When Percy isn’t using his sword, what does it turn into?', 'A ballpoint pen', ['A ring', 'A wristwatch', 'A keychain']],
      ['Who is Annabeth Chase’s godly parent?', 'Athena', ['Aphrodite', 'Artemis', 'Hera']],
      ['What kind of creature is Grover Underwood?', 'A satyr', ['A centaur', 'A cyclops', 'A nymph']],
      ['What is the name of Percy’s Cyclops half-brother?', 'Tyson', ['Polyphemus', 'Brutus', 'Ethan']],
      ['Which centaur trains the heroes at camp?', 'Chiron', ['Pholus', 'Nessus', 'Argus']],
      ['In The Lightning Thief, what is Percy accused of stealing?', 'Zeus’s master bolt', ['Poseidon’s trident', 'Hades’ helm', 'Athena’s shield']],
      ['Who is Luke Castellan’s godly parent?', 'Hermes', ['Ares', 'Apollo', 'Hephaestus']],
      ['Which Titan is the main villain of the first Percy Jackson series?', 'Kronos', ['Atlas', 'Hyperion', 'Prometheus']],
      ['Clarisse La Rue is a daughter of which god?', 'Ares', ['Athena', 'Hephaestus', 'Nemesis']],
      ['Who is Nico di Angelo’s godly parent?', 'Hades', ['Hermes', 'Zeus', 'Poseidon']],
      ['Thalia Grace is a daughter of which god?', 'Zeus', ['Poseidon', 'Hades', 'Apollo']],
      ['What does Annabeth’s magic Yankees cap do?', 'Makes her invisible', ['Lets her fly', 'Lets her read minds', 'Stops time']],
      ['Who wrote the Percy Jackson books?', 'Rick Riordan', ['J.K. Rowling', 'Suzanne Collins', 'Cassandra Clare']],
      ['Which New York building hides the entrance to Mount Olympus?', 'The Empire State Building', ['The Chrysler Building', 'The Statue of Liberty', 'Grand Central Terminal']],
      ['In The Lightning Thief, which city hides the entrance to the Underworld?', 'Los Angeles', ['Las Vegas', 'New York City', 'Chicago']],
      ['What is the name of Percy’s black pegasus?', 'Blackjack', ['Arion', 'Midnight', 'Shadowfax']],
      ['What is the name of Percy’s mom?', 'Sally Jackson', ['May Castellan', 'Maria di Angelo', 'Beryl Grace']],
    ],
  },
  {
    id: 'marvel', name: 'Marvel', icon: '🦸',
    questions: [
      ['What metal is Captain America’s shield made of in the Marvel movies?', 'Vibranium', ['Adamantium', 'Uru', 'Titanium']],
      ['What is the name of Thor’s original hammer?', 'Mjolnir', ['Stormbreaker', 'Gungnir', 'Jarnbjorn']],
      ['What is the name of Tony Stark’s AI assistant in the first Iron Man movies?', 'J.A.R.V.I.S.', ['F.R.I.D.A.Y.', 'Ultron', 'K.A.R.E.N.']],
      ['What is the name of Black Panther’s home country?', 'Wakanda', ['Sokovia', 'Latveria', 'Genosha']],
      ['What is the name of the golden glove Thanos uses to hold the Infinity Stones?', 'The Infinity Gauntlet', ['The Cosmic Cube', 'The Titan Fist', 'The Tesseract']],
      ['How many Infinity Stones are there?', '6', ['5', '7', '8']],
      ['Which actor plays Iron Man in the Marvel movies?', 'Robert Downey Jr.', ['Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo']],
      ['What is the Hulk’s human name?', 'Bruce Banner', ['Bruce Wayne', 'Steve Rogers', 'Clint Barton']],
      ['What kind of animal is Rocket in Guardians of the Galaxy?', 'A raccoon', ['A fox', 'A ferret', 'A red panda']],
      ['What is Star-Lord’s real name?', 'Peter Quill', ['Peter Parker', 'Scott Lang', 'Sam Wilson']],
      ['What was the first movie in the Marvel Cinematic Universe?', 'Iron Man', ['The Incredible Hulk', 'Captain America: The First Avenger', 'Thor']],
      ['Who is Thor’s adopted brother?', 'Loki', ['Odin', 'Heimdall', 'Hela']],
      ['Which hero can shrink to the size of an ant?', 'Ant-Man', ['Hawkeye', 'Falcon', 'Vision']],
      ['Which city do the Avengers defend in the first Avengers movie?', 'New York City', ['Los Angeles', 'Washington, D.C.', 'London']],
      ['What is Black Widow’s real name?', 'Natasha Romanoff', ['Wanda Maximoff', 'Yelena Belova', 'Maria Hill']],
      ['Which Infinity Stone was hidden on the planet Vormir?', 'The Soul Stone', ['The Mind Stone', 'The Time Stone', 'The Power Stone']],
      ['What metal is bonded to Wolverine’s skeleton?', 'Adamantium', ['Vibranium', 'Titanium', 'Uru']],
      ['Which friend of Captain America becomes the Winter Soldier?', 'Bucky Barnes', ['Sam Wilson', 'Nick Fury', 'Brock Rumlow']],
      ['What is Spider-Man’s real name?', 'Peter Parker', ['Miles Morales', 'Harry Osborn', 'Ned Leeds']],
      ['What does the S.H.I.E.L.D. director Nick Fury wear over one eye?', 'An eye patch', ['A monocle', 'A bandage', 'Sunglasses']],
    ],
  },
  {
    id: 'movies', name: 'Movies', icon: '🎬',
    questions: [
      ['Which movie series features the line “May the Force be with you”?', 'Star Wars', ['Star Trek', 'Dune', 'Guardians of the Galaxy']],
      ['What is the name of the cowboy toy in Toy Story?', 'Woody', ['Buzz Lightyear', 'Rex', 'Hamm']],
      ['What kind of fish is Nemo?', 'A clownfish', ['A blue tang', 'An angelfish', 'A pufferfish']],
      ['In The Lion King, what is the name of Simba’s father?', 'Mufasa', ['Scar', 'Rafiki', 'Zazu']],
      ['Which hobbit carries the One Ring to Mordor in The Lord of the Rings?', 'Frodo Baggins', ['Bilbo Baggins', 'Samwise Gamgee', 'Pippin Took']],
      ['Which 1997 movie is about a ship that sinks after hitting an iceberg?', 'Titanic', ['The Poseidon Adventure', 'Pearl Harbor', 'Master and Commander']],
      ['Who directed Jurassic Park?', 'Steven Spielberg', ['James Cameron', 'George Lucas', 'Ridley Scott']],
      ['Which actor played Captain Jack Sparrow?', 'Johnny Depp', ['Orlando Bloom', 'Brad Pitt', 'Leonardo DiCaprio']],
      ['In The Matrix, what color pill does Neo take?', 'Red', ['Blue', 'Green', 'White']],
      ['In Back to the Future, what car is turned into a time machine?', 'A DeLorean', ['A Mustang', 'A Corvette', 'A Camaro']],
      ['In Shrek, what kind of creature falls in love with Donkey?', 'A dragon', ['A unicorn', 'A horse', 'A cat']],
      ['What is the name of the lion in The Chronicles of Narnia?', 'Aslan', ['Mufasa', 'Leo', 'Simba']],
      ['Which movie introduced Gru and his yellow Minions?', 'Despicable Me', ['Megamind', 'Madagascar', 'Monsters, Inc.']],
      ['In the 1939 movie The Wizard of Oz, what color are Dorothy’s slippers?', 'Ruby red', ['Gold', 'Emerald green', 'Sky blue']],
      ['In Home Alone, where is Kevin’s family flying to when they leave him behind?', 'Paris', ['London', 'Rome', 'New York']],
      ['Which actor voices Woody in Toy Story?', 'Tom Hanks', ['Tim Allen', 'Billy Crystal', 'Robin Williams']],
      ['Which 1975 movie about a giant shark made people afraid to go in the water?', 'Jaws', ['The Meg', 'Deep Blue Sea', 'Open Water']],
      ['Which boy wizard movie series is set at Hogwarts?', 'Harry Potter', ['The Chronicles of Narnia', 'Percy Jackson', 'Fantastic Beasts']],
      ['Which actor played Indiana Jones?', 'Harrison Ford', ['Tom Selleck', 'Kevin Costner', 'Mel Gibson']],
      ['In Jurassic Park, what kind of scientist is Dr. Alan Grant?', 'A paleontologist', ['A geneticist', 'A mathematician', 'A zoologist']],
    ],
  },
  {
    id: 'disney', name: 'Disney & Pixar', icon: '🏰',
    questions: [
      ['In Frozen, which sister has ice powers?', 'Elsa', ['Anna', 'Moana', 'Merida']],
      ['What is the name of Aladdin’s monkey?', 'Abu', ['Rajah', 'Iago', 'Pascal']],
      ['In Moana, what is the name of the demigod?', 'Maui', ['Tamatoa', 'Hei Hei', 'Pua']],
      ['In Up, what lifts Carl’s house into the sky?', 'Balloons', ['A blimp', 'A tornado', 'Rockets']],
      ['What is the name of the fairy in Peter Pan?', 'Tinker Bell', ['Fauna', 'Silvermist', 'Flora']],
      ['In Beauty and the Beast, what is the name of the candlestick?', 'Lumière', ['Cogsworth', 'Chip', 'Mrs. Potts']],
      ['What kind of animal is Dumbo?', 'An elephant', ['A mouse', 'A deer', 'A bear']],
      ['Which princess has a pet tiger named Rajah?', 'Jasmine', ['Mulan', 'Pocahontas', 'Tiana']],
      ['In Coco, what instrument does Miguel want to play?', 'The guitar', ['The trumpet', 'The violin', 'The drums']],
      ['In Inside Out, which emotion is blue?', 'Sadness', ['Fear', 'Disgust', 'Anger']],
      ['What does Cinderella leave behind at the ball?', 'A glass slipper', ['A crown', 'A necklace', 'A glove']],
      ['In Toy Story, what is the name of the boy who owns the toys?', 'Andy', ['Sid', 'Bonnie', 'Danny']],
      ['What is the name of Mickey Mouse’s dog?', 'Pluto', ['Goofy', 'Max', 'Chip']],
      ['In Encanto, who do “we not talk about”?', 'Bruno', ['Mirabel', 'Camilo', 'Luisa']],
      ['Which Disney princess has 70 feet of magical hair?', 'Rapunzel', ['Aurora', 'Belle', 'Ariel']],
      ['In Finding Nemo, what is the name of the forgetful blue fish?', 'Dory', ['Marlin', 'Gill', 'Bubbles']],
      ['In Mulan, what is the name of the little red dragon?', 'Mushu', ['Cri-Kee', 'Khan', 'Sisu']],
      ['What are the names of the two monster best friends in Monsters, Inc.?', 'Mike and Sulley', ['Randall and Roz', 'Mike and Randall', 'Sulley and George']],
      ['In The Incredibles, what is Mr. Incredible’s first name?', 'Bob', ['Frank', 'Jack', 'Lucius']],
      ['In The Little Mermaid, what is the name of the sea witch?', 'Ursula', ['Maleficent', 'Cruella', 'Yzma']],
      ['Which Pixar movie is about a rat who dreams of being a chef?', 'Ratatouille', ['Luca', 'Onward', 'Soul']],
    ],
  },
  {
    id: 'tv', name: 'TV & Pop Culture', icon: '📺',
    questions: [
      ['In Friends, what is the name of the coffee shop the gang hangs out in?', 'Central Perk', ['The Grind', 'Café Nervosa', 'Monk’s Café']],
      ['In which town do The Simpsons live?', 'Springfield', ['Shelbyville', 'Quahog', 'South Park']],
      ['In Stranger Things, what is the dark parallel world called?', 'The Upside Down', ['The Nether', 'The Other Side', 'The Void']],
      ['Which TV show is about noble families fighting over the Iron Throne?', 'Game of Thrones', ['The Witcher', 'Vikings', 'The Crown']],
      ['In The Office (US), what paper company do they work for?', 'Dunder Mifflin', ['Wernham Hogg', 'Sabre', 'Staples']],
      ['In Stranger Things, what breakfast food does Eleven love?', 'Eggo waffles', ['Pancakes', 'Pop-Tarts', 'Cereal']],
      ['Where does SpongeBob SquarePants live?', 'In a pineapple under the sea', ['In a rock', 'In a coconut', 'In a shipwreck']],
      ['Which streaming service released Squid Game?', 'Netflix', ['Hulu', 'Disney+', 'Amazon Prime Video']],
      ['In Breaking Bad, what subject does Walter White teach?', 'Chemistry', ['Physics', 'Biology', 'Math']],
      ['Which video game is about building with blocks while avoiding Creepers?', 'Minecraft', ['Roblox', 'Fortnite', 'Terraria']],
      ['Which video game character is a plumber in a red cap?', 'Mario', ['Luigi', 'Wario', 'Sonic']],
      ['In Stranger Things, what is the name of the town where it all happens?', 'Hawkins', ['Derry', 'Riverdale', 'Sunnydale']],
      ['What type of Pokémon is Pikachu?', 'Electric', ['Fire', 'Normal', 'Psychic']],
      ['In The Mandalorian, what do fans nickname the character Grogu?', 'Baby Yoda', ['Little Yoda', 'Yoda Jr.', 'Mini Yoda']],
      ['In Squid Game’s first game, players must freeze when the doll says what?', 'Red light', ['Stop', 'Freeze', 'Halt']],
      ['How many seasons of Friends are there?', '10', ['8', '9', '12']],
      ['Which Pokémon is famous for saying its own name, “Pika pika”?', 'Pikachu', ['Jigglypuff', 'Eevee', 'Togepi']],
      ['Which cartoon family has a dad named Homer?', 'The Simpsons', ['The Griffins', 'The Belchers', 'The Flintstones']],
      ['In Friends, what is Joey’s famous pickup line?', 'How you doin’?', ['What’s up?', 'Hey there', 'You come here often?']],
      ['Which show features the characters Sheldon, Leonard and Penny?', 'The Big Bang Theory', ['Young Sheldon', 'How I Met Your Mother', 'New Girl']],
    ],
  },
  {
    id: 'music', name: 'Music', icon: '🎵',
    questions: [
      ['Which band sang “Hey Jude”?', 'The Beatles', ['The Rolling Stones', 'Queen', 'The Beach Boys']],
      ['Who is known as the King of Pop?', 'Michael Jackson', ['Elvis Presley', 'Prince', 'Justin Timberlake']],
      ['Who is known as the King of Rock and Roll?', 'Elvis Presley', ['Chuck Berry', 'Little Richard', 'Johnny Cash']],
      ['How many strings does a standard guitar have?', '6', ['4', '5', '8']],
      ['Whose fans call themselves Swifties?', 'Taylor Swift', ['Selena Gomez', 'Katy Perry', 'Olivia Rodrigo']],
      ['Which singer released the albums 19, 21 and 25?', 'Adele', ['Rihanna', 'Beyoncé', 'Lady Gaga']],
      ['Which instrument usually has 88 keys?', 'The piano', ['The organ', 'The accordion', 'The xylophone']],
      ['Who sang “Purple Rain”?', 'Prince', ['Stevie Wonder', 'David Bowie', 'Lionel Richie']],
      ['Freddie Mercury was the lead singer of which band?', 'Queen', ['The Rolling Stones', 'Led Zeppelin', 'Aerosmith']],
      ['Which K-pop group sang “Dynamite”?', 'BTS', ['BLACKPINK', 'EXO', 'TWICE']],
      ['Which rapper’s real name is Marshall Mathers?', 'Eminem', ['Drake', 'Jay-Z', 'Kanye West']],
      ['Who sang “Shape of You”?', 'Ed Sheeran', ['Justin Bieber', 'Shawn Mendes', 'Harry Styles']],
      ['In which English city did The Beatles form?', 'Liverpool', ['London', 'Manchester', 'Birmingham']],
      ['Who sang “Bad Guy”?', 'Billie Eilish', ['Olivia Rodrigo', 'Lorde', 'Ariana Grande']],
      ['Beyoncé first became famous as part of which group?', 'Destiny’s Child', ['TLC', 'The Pussycat Dolls', 'The Spice Girls']],
      ['Harry Styles was a member of which band?', 'One Direction', ['Backstreet Boys', '*NSYNC', 'The Wanted']],
      ['Which composer wrote the “Moonlight Sonata”?', 'Beethoven', ['Mozart', 'Bach', 'Chopin']],
      ['Which Michael Jackson album is the best-selling album of all time?', 'Thriller', ['Bad', 'Off the Wall', 'Dangerous']],
      ['Who sang “Hello” with the line “Hello from the other side”?', 'Adele', ['Sam Smith', 'Lionel Richie', 'Amy Winehouse']],
      ['Which singer is known for the hit “Uptown Funk” with Mark Ronson?', 'Bruno Mars', ['Pharrell Williams', 'Justin Timberlake', 'The Weeknd']],
    ],
  },
  {
    id: 'sports', name: 'Sports', icon: '🏆',
    questions: [
      ['How many players does a soccer team have on the field at once?', '11', ['10', '9', '12']],
      ['In which sport would you perform a slam dunk?', 'Basketball', ['Volleyball', 'Tennis', 'Rugby']],
      ['How often are the Summer Olympics held?', 'Every 4 years', ['Every 2 years', 'Every 3 years', 'Every 5 years']],
      ['Which country has won the most men’s FIFA World Cups?', 'Brazil', ['Germany', 'Italy', 'Argentina']],
      ['Which sport is played at Wimbledon?', 'Tennis', ['Golf', 'Cricket', 'Polo']],
      ['How many points is a touchdown worth in American football?', '6', ['3', '7', '2']],
      ['In golf, what is one stroke under par called?', 'A birdie', ['An eagle', 'A bogey', 'An albatross']],
      ['How many rings are on the Olympic flag?', '5', ['4', '6', '7']],
      ['In which sport do teams compete for the Stanley Cup?', 'Ice hockey', ['Baseball', 'Basketball', 'American football']],
      ['How many holes are played in a standard round of golf?', '18', ['9', '12', '21']],
      ['Michael Phelps won most of his Olympic medals in which sport?', 'Swimming', ['Diving', 'Rowing', 'Track']],
      ['What color jersey does the overall leader of the Tour de France wear?', 'Yellow', ['Green', 'Pink', 'Red']],
      ['In baseball, how many strikes make a strikeout?', '3', ['2', '4', '5']],
      ['In which sport is a score of zero called “love”?', 'Tennis', ['Badminton', 'Golf', 'Squash']],
      ['Which city hosted the 2016 Summer Olympics?', 'Rio de Janeiro', ['London', 'Tokyo', 'Beijing']],
      ['How long is a marathon, to the nearest mile?', '26 miles', ['13 miles', '20 miles', '30 miles']],
      ['Which country does Lionel Messi play for internationally?', 'Argentina', ['Spain', 'Portugal', 'Brazil']],
      ['Which boxer called himself “The Greatest”?', 'Muhammad Ali', ['Mike Tyson', 'Floyd Mayweather', 'George Foreman']],
      ['Usain Bolt is famous for which event?', 'Sprinting', ['Long jump', 'Swimming', 'Cycling']],
      ['In which sport do you use a shuttlecock?', 'Badminton', ['Squash', 'Table tennis', 'Lacrosse']],
    ],
  },
  {
    id: 'animals', name: 'Animals', icon: '🐾',
    questions: [
      ['What is the fastest land animal?', 'The cheetah', ['The lion', 'The pronghorn', 'The greyhound']],
      ['What is the largest animal on Earth?', 'The blue whale', ['The African elephant', 'The whale shark', 'The giant squid']],
      ['How many legs does a spider have?', '8', ['6', '10', '12']],
      ['What is a group of lions called?', 'A pride', ['A pack', 'A herd', 'A troop']],
      ['What is the only mammal that can truly fly?', 'The bat', ['The flying squirrel', 'The sugar glider', 'The colugo']],
      ['Which animal is known as the “ship of the desert”?', 'The camel', ['The horse', 'The llama', 'The donkey']],
      ['How many hearts does an octopus have?', '3', ['1', '2', '8']],
      ['What do giant pandas mostly eat?', 'Bamboo', ['Eucalyptus', 'Fish', 'Berries']],
      ['What is the tallest animal in the world?', 'The giraffe', ['The elephant', 'The ostrich', 'The moose']],
      ['What is a baby kangaroo called?', 'A joey', ['A kit', 'A cub', 'A pup']],
      ['What is the largest species of big cat?', 'The tiger', ['The lion', 'The jaguar', 'The leopard']],
      ['What is the largest bird in the world?', 'The ostrich', ['The emu', 'The albatross', 'The condor']],
      ['What color is a polar bear’s skin?', 'Black', ['White', 'Pink', 'Grey']],
      ['Which lizard is famous for changing color?', 'The chameleon', ['The gecko', 'The iguana', 'The komodo dragon']],
      ['Which furry mammal with a duck-like bill lays eggs?', 'The platypus', ['The beaver', 'The otter', 'The mole']],
      ['What kind of animal is a shark?', 'A fish', ['A mammal', 'A reptile', 'An amphibian']],
      ['Which bird is known for copying human speech?', 'The parrot', ['The pigeon', 'The owl', 'The flamingo']],
      ['What is a group of wolves called?', 'A pack', ['A pride', 'A gaggle', 'A school']],
      ['What do caterpillars turn into?', 'Butterflies or moths', ['Beetles', 'Dragonflies', 'Bees']],
      ['Which animal has the longest lifespan: a tortoise, a dog, a horse or a cat?', 'A tortoise', ['A dog', 'A horse', 'A cat']],
    ],
  },
  {
    id: 'food', name: 'Food & Drink', icon: '🍕',
    questions: [
      ['What is the main ingredient in guacamole?', 'Avocado', ['Cucumber', 'Green pepper', 'Peas']],
      ['Sushi comes from which country?', 'Japan', ['China', 'Korea', 'Thailand']],
      ['What is the main ingredient in hummus?', 'Chickpeas', ['Lentils', 'Black beans', 'Peas']],
      ['Which nut is used to make marzipan?', 'Almonds', ['Cashews', 'Walnuts', 'Pistachios']],
      ['Which pasta is shaped like little bow ties?', 'Farfalle', ['Penne', 'Fusilli', 'Rigatoni']],
      ['What is tofu made from?', 'Soybeans', ['Rice', 'Chickpeas', 'Wheat']],
      ['Which spice gives curry its yellow color?', 'Turmeric', ['Paprika', 'Cumin', 'Cinnamon']],
      ['Parmesan cheese comes from which country?', 'Italy', ['France', 'Switzerland', 'Greece']],
      ['Which fruit has its seeds on the outside?', 'The strawberry', ['The raspberry', 'The kiwi', 'The blueberry']],
      ['What is the Italian dessert made with coffee-soaked ladyfingers?', 'Tiramisu', ['Panna cotta', 'Cannoli', 'Gelato']],
      ['Peanuts are not true nuts. What are they?', 'Legumes', ['Seeds', 'Berries', 'Grains']],
      ['What makes bread dough rise?', 'Yeast', ['Salt', 'Sugar', 'Butter']],
      ['Which pastry is used to make éclairs and profiteroles?', 'Choux pastry', ['Puff pastry', 'Filo pastry', 'Shortcrust pastry']],
      ['Which drink is made from fermented grapes?', 'Wine', ['Beer', 'Cider', 'Sake']],
      ['Which Mexican dish is a tortilla folded around melted cheese and grilled?', 'A quesadilla', ['A burrito', 'A taco', 'An enchilada']],
      ['Pizza as we know it was invented in which country?', 'Italy', ['Greece', 'The United States', 'France']],
      ['What vegetable are pickles usually made from?', 'Cucumbers', ['Zucchini', 'Green beans', 'Carrots']],
      ['What is the main ingredient in a traditional Spanish paella?', 'Rice', ['Pasta', 'Potatoes', 'Couscous']],
      ['Which fruit is used to make a piña colada, along with coconut?', 'Pineapple', ['Mango', 'Banana', 'Papaya']],
      ['Which part of a chili pepper holds most of its heat?', 'The white ribs inside', ['The skin', 'The tip', 'The stem']],
    ],
  },
  {
    id: 'spelling', name: 'Spelling Bee', icon: '🐝',
    spelling: [
      { word: 'necessary', sentence: 'It isn’t necessary to shout.', wrong: ['neccessary', 'necesary', 'neccesary'] },
      { word: 'separate', sentence: 'Keep the whites separate from the colors.', wrong: ['seperate', 'separat', 'seprate'] },
      { word: 'definitely', sentence: 'I will definitely be there.', wrong: ['definately', 'definitly', 'defenitely'] },
      { word: 'accommodate', sentence: 'The hotel can accommodate fifty guests.', wrong: ['accomodate', 'acommodate', 'accommadate'] },
      { word: 'rhythm', sentence: 'She clapped along to the rhythm.', wrong: ['rythm', 'rhythem', 'rhytm'] },
      { word: 'embarrass', sentence: 'Please don’t embarrass me in front of my friends.', wrong: ['embarass', 'embarras', 'embaress'] },
      { word: 'conscience', sentence: 'Let your conscience be your guide.', wrong: ['concience', 'consience', 'conscence'] },
      { word: 'occurrence', sentence: 'Rain is a common occurrence here.', wrong: ['occurence', 'ocurrence', 'occurance'] },
      { word: 'millennium', sentence: 'The year 2000 began a new millennium.', wrong: ['millenium', 'milennium', 'millennuim'] },
      { word: 'pharaoh', sentence: 'The pharaoh ruled ancient Egypt.', wrong: ['pharoah', 'pharoh', 'faraoh'] },
      { word: 'guarantee', sentence: 'The TV comes with a two-year guarantee.', wrong: ['garantee', 'guarentee', 'guaruntee'] },
      { word: 'mischievous', sentence: 'The mischievous puppy chewed my shoe.', wrong: ['mischievious', 'mischevious', 'mischivous'] },
      { word: 'restaurant', sentence: 'We ate at an Italian restaurant.', wrong: ['restaraunt', 'resturant', 'restuarant'] },
      { word: 'Wednesday', sentence: 'Our game night is on Wednesday.', wrong: ['Wensday', 'Wednsday', 'Wendesday'] },
      { word: 'privilege', sentence: 'It’s a privilege to be here.', wrong: ['priviledge', 'privelege', 'privilage'] },
      { word: 'questionnaire', sentence: 'Please fill out this questionnaire.', wrong: ['questionaire', 'questionnare', 'qestionnaire'] },
      { word: 'calendar', sentence: 'Mark it on the calendar.', wrong: ['calender', 'calandar', 'calander'] },
      { word: 'occasionally', sentence: 'We occasionally eat out on Fridays.', wrong: ['ocasionally', 'occassionally', 'occasionaly'] },
      { word: 'weird', sentence: 'I had a weird dream last night.', wrong: ['wierd', 'weerd', 'wiered'] },
      { word: 'receive', sentence: 'Did you receive my message?', wrong: ['recieve', 'receeve', 'receve'] },
      { word: 'vacuum', sentence: 'Please vacuum the living room.', wrong: ['vaccum', 'vacuume', 'vaccuum'] },
      { word: 'bureaucracy', sentence: 'The permit got stuck in the bureaucracy.', wrong: ['beaurocracy', 'bureacracy', 'burocracy'] },
    ],
  },
];

// Blank the word out of its example sentence, for the phone-facing prompt. The
// sentence is written to contain the word exactly once.
function blankOut(sentence, word) {
  const i = sentence.toLowerCase().indexOf(word.toLowerCase());
  if (i < 0) return sentence;
  return sentence.slice(0, i) + '_____' + sentence.slice(i + word.length);
}

// Every question, normalised to one shape:
//   { id, category, q, a, wrong: [3], hostQ? }
// `q` is what players read; `hostQ`, when present, is what the host reads out
// instead (spelling: the host says the word, the phones must not show it).
const BANK = {};
for (const cat of CATEGORIES) {
  if (cat.spelling) {
    BANK[cat.id] = cat.spelling.map((s, i) => ({
      id: `${cat.id}-${i}`, category: cat.id,
      q: `Which spelling is right? “${blankOut(s.sentence, s.word)}”`,
      hostQ: `Spell “${s.word}”. As in: “${s.sentence}”`,
      phoneHostQ: 'Spell the word the host reads out.',
      a: s.word, wrong: s.wrong,
    }));
  } else {
    BANK[cat.id] = cat.questions.map(([q, a, wrong], i) => ({ id: `${cat.id}-${i}`, category: cat.id, q, a, wrong }));
  }
}

function categoryList() {
  return CATEGORIES.map(c => ({ id: c.id, name: c.name, icon: c.icon, count: BANK[c.id].length }));
}

function categoryName(id) { return CATEGORIES.find(c => c.id === id)?.name || 'Mixed'; }
function categoryIcon(id) { return CATEGORIES.find(c => c.id === id)?.icon || '🎲'; }
function isCategory(id)   { return !!BANK[id]; }
function questionsIn(id)  { return BANK[id] || []; }
function questionById(id) {
  const cat = String(id || '').replace(/-\d+$/, '');
  return (BANK[cat] || []).find(q => q.id === id) || null;
}

module.exports = { CATEGORIES, categoryList, categoryName, categoryIcon, isCategory, questionsIn, questionById, blankOut };
